# Generated by Django 5.1.6 on 2025-02-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnetcarrera', models.IntegerField()),
                ('carnetanio', models.IntegerField()),
                ('carnetcorrelativo', models.IntegerField()),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pagado', models.BooleanField(default=False)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
